// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Actor struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Age    int      `json:"age"`
	Gender string   `json:"gender"`
	Movies []*Movie `json:"movies"`
}

type Movie struct {
	ID       string   `json:"id"`
	Title    string   `json:"title"`
	Genre    string   `json:"genre"`
	Price    string   `json:"price"`
	Director string   `json:"director"`
	Producer string   `json:"producer"`
	Actors   []*Actor `json:"actors"`
}
